### ISSUE TITLE
Error when opening work item with multi value control: Active work item document does not exist in the current context

### ISSUE THREAD

**Issue by sarukk** [microsoft/vsts-extension-multivalue-control#301]
Hi,

We have a field added to a XML template with usage of a multi-value control. It was working for some small amount of time, but now, when we're opening the work items with this field (Test Case), console of web browser reports exceptions, and the filed cannot be filled (suggestions are not being loaded).

Exception itself:

`{stack: 'Error: Active work item document does not exist in…j5dkjJ25uNQ5uBRNIJBWQra743XRca55-UQJdVE=:97:10039', message: 'Active work item document does not exist in the current context', name: 'Error'}
message
: 
"Active work item document does not exist in the current context"
name
: 
"Error"
stack
: 
"Error: Active work item document does not exist in the current context\n    at W._getWorkItem (https://cdn.vsassets.io/ext/ms.vss-work-web/new-work-item-form-extension/ms.vss-work-web.new-work-item-form-extension.es6.hEhPRu.min.js:1:10534)\n    at W.getFieldValue (https://cdn.vsassets.io/ext/ms.vss-work-web/new-work-item-form-extension/ms.vss-work-web.new-work-item-form-extension.es6.hEhPRu.min.js:1:2452)\n    at _proxyFunctions.<computed> (https://cdn.vsassets.io/bundles/vss-bundle-common-vptJBj5dkjJ25uNQ5uBRNIJBWQra743XRca55-UQJdVE=:97:8235)\n    at i.invokeMethod (https://cdn.vsassets.io/bundles/vss-bundle-common-vptJBj5dkjJ25uNQ5uBRNIJBWQra743XRca55-UQJdVE=:97:4168)\n    at i.onMessage (https://cdn.vsassets.io/bundles/vss-bundle-common-vptJBj5dkjJ25uNQ5uBRNIJBWQra743XRca55-UQJdVE=:97:4693)\n    at n._handleMessageReceived (https://cdn.vsassets.io/bundles/vss-bundle-common-vptJBj5dkjJ25uNQ5uBRNIJBWQra743XRca55-UQJdVE=:97:9709)\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vptJBj5dkjJ25uNQ5uBRNIJBWQra743XRca55-UQJdVE=:97:10039"`

**Comment by AminTi** [comment]
Hi, thanks for reporting this. Please check this link: https://github.com/Microsoft/vsts-extension-multivalue-control/blob/master/xmldetails.md. Can you describe your environment? Additionally, can you check if you get any errors in the browser console or network log?

**Comment by sarukk** [comment]
Hi,

The process is based on XML-template. 
Field with this extensions was working for some time, but lately it stopped (I used the above read me file to set it up). The error/exception from my first post is from browser console.

Br,
Damian

**Comment by adamlonsdale** [comment]
I'm seeing this exact same error suddenly starting in a few ADO Projects and shown in the browser console
